ARG BASE_IMAGE
FROM nvidia/cuda:11.4.0-devel-ubuntu20.04 AS nvidia_base

COPY qemu /usr/bin/

RUN apt-get update && apt-get install -y build-essential curl g++ autoconf

COPY build-ffmpeg /

ENV SKIPINSTALL=yes VERBOSE=yes

VOLUME /build
WORKDIR /build

CMD /build-ffmpeg --build